### ISSUE TITLE
KeyError: 'hard_negative_ctxs'

### ISSUE THREAD

**Issue by rahulmool** [khuangaf/CONCRETE#2]
on running run_xict.sh i get the following error.

Traceback (most recent call last):
  File "run_xict.py", line 600, in <module>
    main()
  File "run_xict.py", line 590, in main
    trainer.run_train()
  File "run_xict.py", line 132, in run_train
    self._train_epoch(scheduler, epoch, eval_step, train_iterator)
  File "run_xict.py", line 325, in _train_epoch
    shuffle_positives=args.shuffle_positive_ctx
  File "/scratch/22cs60r72/InformationRetrival/copy/CORA/mDPR/mool/lib/python3.7/site-packages/dpr/models/biencoder.py", line 171, in create_biencoder_input
    hard_neg_ctxs = sample["hard_negative_ctxs"]
KeyError: 'hard_negative_ctxs'

In the dataset "../../data/bbc_passages/all_ict_samples.jsonl_[0,1,2]" there is no argument 'hard_negative_ctxs'
I feel like a part of the code is missing of dpr/models/biencoder.py  Can you share me the code?

**Comment by khuangaf** [comment]
If I recall correctly, we did not use hard negative samples at all. I think you can just set this variable to an empty list.

**Comment by khuangaf** [comment]
Update: Please modify the `create_biencoder_input` function following [this thread](https://github.com/khuangaf/CONCRETE/issues/3).
