### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by rahulmool** [khuangaf/CONCRETE#4]
When i run run_xict.sh I get the following error:-

Traceback (most recent call last):
  File "run_xict.py", line 600, in <module>
    main()
  File "run_xict.py", line 590, in main
    trainer.run_train()
  File "run_xict.py", line 132, in run_train
    self._train_epoch(scheduler, epoch, eval_step, train_iterator)
  File "run_xict.py", line 363, in _train_epoch
    self.validate_and_save(epoch, train_data_iterator.get_iteration(), scheduler)
  File "run_xict.py", line 148, in validate_and_save
    validation_loss = self.validate_nll()
  File "run_xict.py", line 185, in validate_nll
    total_loss = total_loss / batches
ZeroDivisionError: float division by zero

What should I do?

**Comment by khuangaf** [comment]
It's likely that the dev data is not loaded properly, causing `batches` to be zero. You should check this line and see if the data loader is correct https://github.com/khuangaf/CONCRETE/blob/master/CORA/mDPR/run_xict.py#L164.
